# Generated by Django 6.1 on 2026-08-15 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_quality', models.CharField(choices=[('standard', 'Standard'), ('hi-fi', 'High Fidelity'), ('spatial', 'Lossless Spatial')], default='standard', max_length=20)),
                ('app_volume', models.IntegerField(default=80)),
                ('hardware_acceleration', models.BooleanField(default=True)),
                ('auto_lyrics_scroll', models.BooleanField(default=True)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('notif_releases', models.BooleanField(default=True)),
                ('notif_playlists', models.BooleanField(default=True)),
                ('notif_system', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
