# Generated by Django 6.1 on 2026-08-14 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_seconds', models.PositiveIntegerField(default=0, help_text='How many seconds the user listened to during this play event.')),
                ('song_duration_seconds', models.PositiveIntegerField(default=0, help_text='Duration of the song at the time of playback.')),
                ('completed', models.BooleanField(default=False, help_text='True if the user listened to most or all of the song.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='playlists.playlist')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plays', to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tracking_so_user_id_1132b9_idx'), models.Index(fields=['song', '-created_at'], name='tracking_so_song_id_63fa36_idx')],
            },
        ),
    ]
